name: hola-mundo
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: aprendiendo-github-actions
      - name: Define-variables
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: run-script
        run: python hello_world.py
